M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Sun Oct 29 19:46:24 2023
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2023-10-29T19:46:24-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X-1201Y-10827
X1941Y-10827
T0
M30
